# Generated by Django 3.2.9 on 2021-12-15 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internshipapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Post',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('weight', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('created_at', models.CharField(max_length=50)),
                ('updated_at', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Product',
            },
        ),
    ]
