# Generated by Django 3.2.9 on 2021-12-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internshipapp', '0002_post_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='email',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='first_name',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='last_name',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='password',
        ),
        migrations.RemoveField(
            model_name='post',
            name='username',
        ),
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.CharField(default='uu', max_length=500),
            preserve_default=False,
        ),
    ]
