# Generated by Django 3.2.9 on 2021-12-15 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internshipapp', '0003_auto_20211215_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
                ('Category', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Login',
            },
        ),
    ]
